-- Core schema for the Cloud Deployment Control Center.
-- Written in portable SQL so the same migration runs on PostgreSQL (local + RDS)
-- and on H2 in PostgreSQL mode (unit/integration tests).

CREATE TABLE applications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)  NOT NULL,
    description     VARCHAR(1000),
    repository_url  VARCHAR(500)  NOT NULL,
    default_branch  VARCHAR(100)  NOT NULL DEFAULT 'main',
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_applications_name UNIQUE (name)
);

CREATE TABLE environments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id        BIGINT       NOT NULL,
    name                  VARCHAR(30)  NOT NULL,
    url                   VARCHAR(500),
    current_version       VARCHAR(100),
    status                VARCHAR(20)  NOT NULL,
    health_status         VARCHAR(20)  NOT NULL,
    last_health_check_at  TIMESTAMP WITH TIME ZONE,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_environments_application FOREIGN KEY (application_id)
        REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT uq_environments_application_name UNIQUE (application_id, name),
    CONSTRAINT ck_environments_status
        CHECK (status IN ('NOT_DEPLOYED', 'DEPLOYING', 'ACTIVE', 'FAILED')),
    CONSTRAINT ck_environments_health_status
        CHECK (health_status IN ('UNKNOWN', 'HEALTHY', 'UNHEALTHY'))
);

CREATE TABLE deployments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id  BIGINT        NOT NULL,
    environment_id  BIGINT        NOT NULL,
    version         VARCHAR(100)  NOT NULL,
    image_tag       VARCHAR(128)  NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    is_rollback     BOOLEAN       NOT NULL DEFAULT FALSE,
    message         VARCHAR(1000),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE,
    completed_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_deployments_application FOREIGN KEY (application_id)
        REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT fk_deployments_environment FOREIGN KEY (environment_id)
        REFERENCES environments (id) ON DELETE CASCADE,
    CONSTRAINT ck_deployments_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'ROLLED_BACK'))
);

CREATE INDEX idx_environments_application ON environments (application_id);
CREATE INDEX idx_deployments_environment_created ON deployments (environment_id, created_at);
CREATE INDEX idx_deployments_application ON deployments (application_id);
CREATE INDEX idx_deployments_status ON deployments (status);
